#!/bin/bash -p

# EMBA - EMBEDDED LINUX ANALYZER
#
# Copyright 2020-2024 Siemens Energy AG
#
# EMBA comes with ABSOLUTELY NO WARRANTY. This is free software, and you are
# welcome to redistribute it under the terms of the GNU General Public License.
# See LICENSE file for usage of this software.
#
# EMBA is licensed under GPLv3
# SPDX-License-Identifier: GPL-3.0-only
#
# Author(s): Michael Messner

# Description:  This module generates a minimal json SBOM from the identified software inventory
#               via cyclonedx - https://github.com/CycloneDX/cyclonedx-cli#csv-format

F21_cyclonedx_sbom() {
  module_log_init "${FUNCNAME[0]}"
  module_title "CycloneDX SBOM converter"
  pre_module_reporter "${FUNCNAME[0]}"

  local lVERSION=""
  local lCHKSUM=""
  # local lBIN_NAME=""
  # local lSTRIPPED_VER=""
  local lLICENSE=""
  local lTYPE=""
  local lMIME_TYPE=""
  local lSUPPLIER=""
  local lCPE=""
  local lPURL=""
  local lNEG_LOG=0

  if ! command -v cyclonedx > /dev/null; then
    module_end_log "${FUNCNAME[0]}" "${lNEG_LOG}"
    return
  fi

  if [[ -f "${S08_CSV_LOG}" ]] && [[ "$(wc -l "${S08_CSV_LOG}" | awk '{print $1}')" -gt 1 ]]; then
    if [[ -f "${F21_CSV_LOG}" ]]; then
      rm "${F21_CSV_LOG}"
    fi
    if [[ -f "${CSV_DIR}"/f21_cyclonedx_sbom.json ]]; then
      rm "${CSV_DIR}"/f21_cyclonedx_sbom.json
    fi

    write_csv_log "Type" "MimeType" "Supplier" "Author" "Publisher" "Group" "Name" "Version" "Scope" "LicenseExpressions" "LicenseNames" "Copyright" "Cpe" "Purl" "Modified" "SwidTagId" "SwidName" "SwidVersion" "SwidTagVersion" "SwidPatch" "SwidTextContentType" "SwidTextEncoding" "SwidTextContent" "SwidUrl" "MD5" "SHA-1" "SHA-256" "SHA-512" "BLAKE2b-256" "BLAKE2b-384" "BLAKE2b-512" "SHA-384" "SHA3-256" "SHA3-384" "SHA3-512" "BLAKE3" "Description"
    print_output "[*] Collect available SBOM details ..." "no_log"

    # we build a csv that can be handled via cyclonedx
    while IFS=";" read -r COL1 COL2 COL3 COL4 COL5 COL6 COL7; do
      print_output "[*] Generating SBOM entry: ${COL1} - ${COL2} - ${COL4} - ${COL5} - ${COL6} - ${COL7}" "no_log"
      lTYPE="${COL1}"
      # we currently hard code it to application - Todo: we need to define further rules
      lTYPE=""
      # local lBINARY="${COL2}"
      lCHKSUM="${COL3}"
      lBIN_NAME="${COL4}"
      # COL5 -> identified version
      lVERSION="${COL5}"
      if [[ "${COL6}" == "NA" ]]; then
        lSTRIPPED_VER="${COL5}"
      else
        # already post-processed version
        lSTRIPPED_VER="${COL6}"
      fi
      lLICENSE="${COL7}"
      # local lBOM_REF="bom-ref-todo"
      # Todo: we need to define this more in detail (image, font, executable, ...)
      lMIME_TYPE="executable"
      # The supplier may often be the manufacturer, but may also be a distributor or repackager.
      lSUPPLIER="${FW_VENDOR:-unknown}"
      lCPE=""
      lPURL=""
      lDESCRIPTION="SBOM generated by EMBA - type ${COL1} - originally identified version ${COL5}"
      write_csv_log "${lTYPE}" "${lMIME_TYPE}" "${lSUPPLIER}" "" "" "" "${lBIN_NAME}" "${lSTRIPPED_VER:-NA}" "" "" "${lLICENSE:-NA}" "" "${lCPE}" "${lPURL}" "" "" "" "" "" "" "" "" "" "" "" "" "" "${lCHKSUM}" "" "" "" "" "" "" "" "" "${lDESCRIPTION}"
    done < <(tail -n +2 "${S08_CSV_LOG}" | sort -u)

    if [[ -f "${F21_CSV_LOG}" ]]; then
      print_output "[*] Converting CSV SBOM to Cyclonedx SBOM ..." "no_log"
      # our csv is with ";" as deliminiter. cyclonedx needs "," -> lets do a quick tranlation
      sed -i 's/\;/,/g' "${F21_CSV_LOG}"
      cyclonedx convert --input-file "${F21_CSV_LOG}" --output-file "${LOG_PATH_MODULE}"/f21_cyclonedx_sbom_json.json || true
    fi

    if [[ -f "${LOG_PATH_MODULE}"/f21_cyclonedx_sbom_json.json ]]; then
      print_output "[+] Cyclonedx SBOM in json and CSV format created:"
      print_output "$(indent "$(orange "-> Download JSON${NC}")")" "" "${LOG_PATH_MODULE}/f21_cyclonedx_sbom_json.json"
      print_output "$(indent "$(orange "-> Download CSV${NC}")")" "" "${F21_CSV_LOG}"
      print_ln
      print_output "[+] Cyclonedx SBOM in json format:"
      print_ln
      tee -a "${LOG_FILE}" < "${LOG_PATH_MODULE}"/f21_cyclonedx_sbom_json.json
      print_ln
      local lNEG_LOG=1
    fi
  fi

  module_end_log "${FUNCNAME[0]}" "${lNEG_LOG}"
}
