#!/bin/sh
# /etc/cron.daily/emba_updater: Daily EMBA maintenance script
# Written by Michael Messner and Pascal Eckmann for EMBA https://github.com/e-m-b-a/emba

[ -x /home/benedikt/emba_fork/external/cve-search/sbin/db_updater.py ] || exit 0
[ -x /etc/init.d/redis-server ] || exit 0

echo "[*] EMBA update - cve_searchsploit update" | tee -a /var/log/emba_update.log
cve_searchsploit -u | tee -a /var/log/emba_update.log

echo "[*] EMBA update - cve-search update" | tee -a /var/log/emba_update.log
/etc/init.d/redis-server start | tee -a /var/log/emba_update.log

/home/benedikt/emba_fork/external/cve-search/sbin/db_updater.py -v | tee -a /var/log/emba_update.log

echo "[*] EMBA update - update local docker image" | tee -a /var/log/emba_update.log
docker pull embeddedanalyzer/emba | tee -a /var/log/emba_update.log
#TODO change to simple rebuild of docker images and rm .cve_search_data