#!/bin/bash

print_output "The CycloneX SBOM module generates a Software Bill of Materials (SBOM) in JSON format by processing vulnerability data through CycloneDX and then logging and storing the SBOM in the log directory."