name: First interaction

on:
  - pull_request_target
  - issues

permissions:
  issues: write
  pull-requests: write

jobs:
  first-interaction:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest

    steps:
    - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d  # v3.1.0 - https://github.com/actions/first-interaction/releases/tag/v3.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        issue-message: |
          Thank you for contributing an issue!

          **Welcome to the EMBA firmware analysis community!**

          We are glad you are here and appreciate your contribution. Please keep in mind our contributing guidelines [here](https://github.com/e-m-b-a/emba/blob/master/CONTRIBUTING.md) and [here](https://github.com/e-m-b-a/emba/blob/master/CONTRIBUTORS.md).
          Also, please check [existing open issues](https://github.com/e-m-b-a/emba/issues) and consider to open a discussion in the dedicated [discussion area](https://github.com/e-m-b-a/emba/discussions).
          Additionally, we have collected a lot of details around EMBA, the installation and the usage of EMBA in our [Wiki](https://github.com/e-m-b-a/emba/wiki).

          If you like _EMBA_ you have the chance to support us by becoming a [Sponsor](https://github.com/sponsors/e-m-b-a) or buying some beer [here](https://www.buymeacoffee.com/securefirmware).

          To show your love for _EMBA_ with nice shirts or other merch you can check our [Spreadshop](https://emba-firmware-analyzer.myspreadshop.de/).

          This is an automatic message. Allow for time for the EMBA community to be able to read the issue and comment on it.

        pr-message: |
          Thank you for contributing a pull request!

          **Welcome to the EMBA firmware analysis community!**

          We are glad you are here and appreciate your contribution. Please keep in mind our contributing guidelines [here](https://github.com/e-m-b-a/emba/blob/master/CONTRIBUTING.md) and [here](https://github.com/e-m-b-a/emba/blob/master/CONTRIBUTORS.md).
          Also, please check [existing open issues](https://github.com/e-m-b-a/emba/issues) and consider to open a discussion in the dedicated [discussion area](https://github.com/e-m-b-a/emba/discussions).
          Additionally, we have collected a lot of details around EMBA, the installation and the usage of EMBA in our [Wiki](https://github.com/e-m-b-a/emba/wiki).

          If you like _EMBA_ you have the chance to support us by becoming a [Sponsor](https://github.com/sponsors/e-m-b-a) or buying some beer [here](https://www.buymeacoffee.com/securefirmware).

          To show your love for _EMBA_ with nice shirts or other merch you can check our [Spreadshop](https://emba-firmware-analyzer.myspreadshop.de/).
          
          This is an automatic message. Allow for time for the EMBA community to be able to read the pull request and comment on it.
