name: Update GCC version database

on:
  schedule:
    - cron: '0 0 * * 0' # do it every week
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_gcc_db:
    if: github.repository_owner == 'e-m-b-a'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
    - name: Install requirements
      run: |
        sudo apt-get update -y
        sudo apt-get install curl -y
    - name: update GCC version db
      run: |
        ./helpers/generate_gcc_info.sh || exit 1
        ./helpers/generate_gcc_libstdc_info.sh || exit 1
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update GCC version database
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: gcc_update
        delete-branch: true
        title: 'GCC version database update'
        body: |
          Update report
          - Updated latest GCC version details
        labels: |
          db_update
          automated pr
        milestone: 0
        draft: false
