# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: lychee
on:
  schedule:
    - cron: '0 0 * * *' # do it every day
  push:
    branches:
      - '**'        # matches every branch
  pull_request:
    branches:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lychee-link-check:
    if: github.repository_owner == 'e-m-b-a'
    name: Link check
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2 - https://github.com/actions/checkout/releases/tag/v6.0.2

      - name: Link Checker
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411  # v2.8.0 - https://github.com/lycheeverse/lychee-action/releases/tag/v2.8.0
        with:
          fail: true
