name: Update packetstorm database

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # do it every week

jobs:
  update_packetstorm_db:
    if: github.repository_owner == 'e-m-b-a'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
    - name: Install requirements
      run: |
        sudo apt-get update -y
        sudo apt-get install lynx
    - name: update packetstorm db
      run: |
        ./helpers/packet_storm_crawler.sh
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update packetstorm database
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: packetstorm_update
        delete-branch: true
        title: 'Packetstorm database update'
        body: |
          Update report
          - Updated latest packetstorm exploits
        labels: |
          db_update
          automated pr
        milestone: 0
        draft: false
