name: Update Routersploit database

on:
  schedule:
    - cron: '0 0 * * 1' # do it every week

jobs:
  update_routersploit_db:
    if: github.repository_owner == 'e-m-b-a'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
    - name: Install requirements
      run: |
        sudo apt-get update -y
        sudo apt-get install git
        mkdir external
        git clone --branch dev_rework https://github.com/GH0st3rs/routersploit.git external/routersploit
    - name: update routersploit db
      run: |
        ./helpers/routersploit_db_update.sh /home/runner/work/emba/emba/external/routersploit/routersploit/modules
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update Routersploit database
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: routersploit_update
        delete-branch: true
        title: 'Routersploit database update'
        body: |
          Update report
          - Updated latest Routersploit exploits
        labels: |
          db_update
          automated pr
        milestone: 0
        draft: false
