name: Check Formatting with shfmt

on:
  push:
    branches:
      - '**'        # matches every branch
  pull_request:
    branches:
      - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  shfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2 - https://github.com/actions/checkout/releases/tag/v6.0.2

      - name: Setup shfmt
        uses: mfinelli/setup-shfmt@a25fda4c1fe115aec0f85e04126610841bc3141d # v4.0.1 - https://github.com/mfinelli/setup-shfmt/releases/tag/v4.0.1

      - name: Run shfmt check
        # -d: Diff anzeigen (zeigt Fehler im Log)
        # -i 2: Prüft auf exakt 2 Leerzeichen Einrückung
        run: shfmt -d -i 2 .
