# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy
on:
  schedule:
    - cron: '0 0 * * 1' # run every Monday
  # push:
  #  branches:
  #    - '**'        # matches every branch
  # pull_request:
  #  branches:
  #    - '**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
#    if: github.repository_owner == 'e-m-b-a'
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Trivy EMBA image check
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout EMBA
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2 - https://github.com/actions/checkout/releases/tag/v6.0.2

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be    # v1.3.1 - https://github.com/jlumbroso/free-disk-space/releases/tag/v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true

      - name: Generate tarball from image
        run: |
          docker pull embeddedanalyzer/emba
          docker save -o emba-image.tar embeddedanalyzer/emba

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@0.35.0
        with:
          input: /github/workspace/emba-image.tar
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@7434149006143a4d75b82a2f411ef15b03ccc2d7  # https://github.com/github/codeql-action/tree/7434149006143a4d75b82a2f411ef15b03ccc2d7
        with:
          sarif_file: 'trivy-results.sarif'

